xdg_data_home:
  x86_64:  "<%= ENV['HOME'] %>/ondemand/x86_64"
  aarch64: "<%= ENV['HOME'] %>/ondemand/aarch64"

container_image:
  x86_64:  /cloud_opt/ondemand/rocky97_x86_64.sif
  aarch64: /cloud_opt/ondemand/rocky97_aarch64.sif
